services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aws_global_router_backend_prod
    restart: always
    env_file:
      - ./secrets/.prod.env
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]
    networks:
      - router_net

  frontend:
    build:
      context: ./frontend
      target: production
      dockerfile: Dockerfile
    container_name: aws_global_router_frontend_prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - router_net

networks:
  router_net:
    driver: bridge
